openapi: 3.0.1
info:
  title: TikTok Shop Auth API
  version: 1.0.0
  description: Exchange authorization code for an access token from TikTok Shop.
servers:
  - url: https://auth.tiktok-shops.com/api/v2
paths:
  /token/get:
    get:
      summary: Exchange authorization code for access token
      description: |
        Retrieves an access token using an authorization code.
      parameters:
        - name: app_key
          in: query
          required: true
          schema:
            type: string
          example: 123abcd
        - name: app_secret
          in: query
          required: true
          schema:
            type: string
          example: 15abf8a4972afd1f275d5b19bfa9a17e0d142aa7
        - name: auth_code
          in: query
          required: true
          schema:
            type: string
          example: TTP_FeBoANmHP3yqdoUI9fZOCw
        - name: grant_type
          in: query
          required: true
          schema:
            type: string
            enum: [authorized_code]
          example: authorized_code
      responses:
        '200':
          description: Successful token exchange
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  message:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: ROW_msbfyQAAAAAeb4vVdgdh9LsSb0VCRPeHFrnfePrp8bi_IzAaYpv9vgPKW2Q1iUTH_3-NYqMruZyfhy5I-j85r62xKr6XUC8JfmDNqO-XRTLXd5J6NCFptDbKwxvK3numNfLKsxHRdnTIzyfh9dn8gx6P9a_rUE0qsIjx9VB30rkJOSEa2HFE-ngo9RfDPvvhjOj3xSSrgTtwxRwIL-UM5YG05pPEcbpq4Re512FVejPbkDEwWWCYraeD8EewnojhjOpA2YgGVlO6cfkLT63TqhXRlqtnAAkLhzbF4GfxOXelqp-vlj78Yj_KSFQSVemASRAxJBq0U_LjKmVW_0YWIF9qodrfoK5M3LxAZxXBKby6hVhdUlczGYD38Yecre58BEdLYxfbO_xfbOsS11giADdFrxiJVCztIBTjFxxKSA7GmECBLJUcD6AuIid0x_SG-ELSJ6wU-Id2Rpp1oqOYbES78rHIHXj18apH6ORAGzCJx8CYA-1w-_EY6SpSpYv7vLHzvM3UMjE
                      access_token_expire_in:
                        type: integer
                        example: 1750326180
                      refresh_token:
                        type: string
                        example: ROW_H7Iv_AAAAAA2cVHgCzLzf3k1lef_2om81JL5fgeJfIA6SBr_tKMWKEtAlOhKFVrCC66aGKuGdfU
                      refresh_token_expire_in:
                        type: integer
                        example: 1757495562
                      open_id:
                        type: string
                        example: 7_qR9gAAAACGdr0JbCFBeZ0z1RUEZYl-6Wv94wV_MMrA4vHE3qzTzw
                      seller_name:
                        type: string
                        example: SANDBOX7510131124003129144
                      seller_base_region:
                        type: string
                        example: VN
                      user_type:
                        type: integer
                        example: 0
                      granted_scopes:
                        type: array
                        items:
                          type: string
                        example: ["seller.api_testing_tool.02", "QA TEST"]
                  request_id:
                    type: string
        '400':
          description: Bad request (missing/invalid parameters)
        '401':
          description: Unauthorized (invalid app_key/app_secret)


